# Generated by Django 3.0.6 on 2020-07-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Проектировщики',
                'verbose_name_plural': 'Проектировщики',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('result_CO2_1', models.TextField()),
                ('result_CO2_2', models.TextField()),
            ],
            options={
                'verbose_name': 'Результаты',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('diameter_PPU', models.IntegerField()),
                ('vvoda_PPU', models.IntegerField()),
                ('nopora_PPU', models.IntegerField()),
                ('diameter_IZOP', models.IntegerField()),
                ('vvoda_IZOP', models.IntegerField()),
                ('nopora_IZOP', models.IntegerField()),
                ('width_mon', models.IntegerField()),
                ('height_mon', models.IntegerField()),
                ('m_mon', models.IntegerField()),
                ('width_bez_1', models.IntegerField()),
                ('m_bez_1', models.IntegerField()),
                ('width_bez_2', models.IntegerField()),
                ('m_bez_2', models.IntegerField()),
                ('l6_sht', models.IntegerField()),
                ('l6_l', models.IntegerField()),
                ('l6_dl', models.IntegerField()),
                ('l6_pl', models.IntegerField()),
                ('l6_dpl', models.IntegerField()),
                ('l11_sht', models.IntegerField()),
                ('l11_l', models.IntegerField()),
                ('l11_dl', models.IntegerField()),
                ('l11_pl', models.IntegerField()),
                ('l11_dpl', models.IntegerField()),
                ('fbs336', models.IntegerField()),
                ('fbs636', models.IntegerField()),
                ('fbs936', models.IntegerField()),
                ('fbs1236', models.IntegerField()),
                ('fbs2436', models.IntegerField()),
                ('podb_B15', models.IntegerField()),
                ('sil_PPU', models.IntegerField()),
                ('sil_IZOP', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='mat_vvoda.Author')),
            ],
            options={
                'verbose_name': 'Коэффициенты',
                'verbose_name_plural': 'Коэффициенты',
            },
        ),
    ]
