# Generated by Django 3.0.6 on 2020-06-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat_vvoda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сoefficients',
            options={'verbose_name': 'Коэффициенты', 'verbose_name_plural': 'Коэффициенты'},
        ),
    ]
