# Generated by Django 3.0.6 on 2020-06-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat_vvoda', '0002_auto_20200622_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сoefficients',
            new_name='Сoefficient',
        ),
    ]
