# Generated by Django 3.0.6 on 2020-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_vvoda', '0003_auto_20200622_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='сoefficient',
            name='name_author',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
